SELECT SEGMENT_NAME, SUM(BYTES) BYTES, ceil(SUM(BYTES) / (1024 * 1024)) MB
  FROM DBA_SEGMENTS
 WHERE OWNER = 'MIND'
   AND SEGMENT_NAME LIKE 'ACTIVECALLS%'
   AND SEGMENT_NAME NOT LIKE '%ERROR%'
 GROUP BY SEGMENT_NAME;
 